# Generated by Django 2.1.7 on 2019-03-01 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uservs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('feedback', models.TextField(blank=True)),
                ('date_inscription', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_feedback', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
