# Generated by Django 2.1.7 on 2019-03-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivaliers', '0002_auto_20190301_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalier',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
