# Generated by Django 2.1.7 on 2019-03-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('pays', models.CharField(blank=True, max_length=70)),
                ('description', models.TextField(blank=True)),
                ('path_photo', models.CharField(blank=True, max_length=300)),
                ('scene', models.CharField(max_length=30)),
                ('jour', models.CharField(max_length=15)),
                ('horaire_debut', models.DateTimeField(null=True)),
                ('horaire_fin', models.DateTimeField(null=True)),
                ('rs_link_1', models.CharField(blank=True, max_length=450)),
                ('rs_link_2', models.CharField(blank=True, max_length=450)),
                ('rs_link_3', models.CharField(blank=True, max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.TextField(max_length=100)),
                ('page', models.TextField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=25)),
                ('message', models.TextField()),
                ('lien', models.TextField(blank=True, null=True)),
                ('date_pop', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=25)),
                ('heure_debut', models.DateTimeField(null=True)),
                ('heure_fin', models.DateTimeField(null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
